### ISSUE TITLE
pcpartpicker-scraper vs. pcpartpicker

### ISSUE THREAD

**Issue by athenawisdoms** [JonathanVusich/pcpartpicker-scraper#5]
What motivated the creation of [`pcpartpicker-scraper`](https://github.com/JonathanVusich/pcpartpicker-scraper) shortly after building [`pcpartpicker`](https://github.com/JonathanVusich/pcpartpicker)?

Why did you choose to use Selenium in `pcpartpicker-scraper`, instead of the lighter weight `aiohttp` in `pcpartpicker`?

Thank you in advance for any insights!

**Comment by JonathanVusich** [comment]
Lots of motivations. The main reason I created a separate scraper was because pcpartpicker.com would periodically stumble when hit with a lot of asynchronous requests. Also, they started blocking the IP of my main dev machine, since I would have to test against their servers while developing. So I am now using this scraper to take snapshots of the website periodically, and making the data available to the `pcpartpicker` API through Github Pages. This way only one set of requests is made to pcpartpicker.com, they don't have to deal with a ton of extra traffic and no one using the `pcpartpicker` API unwittingly gets their IP blocked. Also, since the info is reduced to JSON the amount of traffic to Github Pages is pretty minimal.

And the reason I used `selenium` for this project over `aiohttp` was so that the requests would be a little more life-like.

**Comment by athenawisdoms** [comment]
Thank you for the detailed explanation! How long was your IP blocked for?

**Comment by JonathanVusich** [comment]
I'm not exactly sure, I think it was around a month.

**Comment by JonathanVusich** [comment]
I'm going to go ahead and close this issue to tidy up the repository.
